name    '3fs-nginx'
version '1.0.0'
source 'http://github.com/3fs/puppet-nginx'
author 'James Fryman'
license 'Apache License Version 2.0'
summary 'Puppet NGINX management module'
description 'This module can be used for basic NGINX Management'
project_page 'http://github.com/3fs/puppet-nginx'

dependency 'puppetlabs/stdlib', '>= 0.1.6'
dependency 'puppetlabs/apt', '>= 1.0.0'
